#!/usr/bin/env bash

testcount=$(build/sunneed -c)

if [[ $testcount == 0 ]]; then
    echo "No runtime tests available." >&2
    exit
fi

echo "Found $testcount tests"

for i in `seq 0 $((testcount - 1))`; do
    echo -n "Running test #$i... "
    build/sunneed -t $i
    code=$?
    if [[ $code != 0 ]]; then
        echo "$(tput setaf 1)Failed: $code$(tput setaf 9)"
    else
        echo "$(tput setaf 2)Success!"
    fi
done
