#!/usr/bin/env bash

if [[ ! -f "$1" ]]; then
    echo "invalid test file" >&2
    exit 1
fi

filename=$1
testname=${1%.c}
header_file=${testname}.h

functions=$(grep -E '^MunitResult ' "$1" | sed -r 's/^MunitResult ([[:alnum:]_]+)\(.*$/\1/')

&>"$header_file"
exec 1>>"$header_file"

echo '#include "test.h"'

for f in ${functions[@]}; do
    echo "MunitResult ${f}(const MunitParameter params[], void *data);"
done

echo "static MunitTest ${testname}_tests[] = {"
for f in ${functions[@]}; do
    echo "{ (char*) (\"/${f}\"), $f, NULL, NULL, MUNIT_TEST_OPTION_NONE, NULL },"
done
echo "{ NULL, NULL, NULL, NULL, MUNIT_TEST_OPTION_NONE, NULL } };"

echo "static const MunitSuite ${testname}_suite = { \"/$testname\", ${testname}_tests, NULL, 1, MUNIT_SUITE_OPTION_NONE };"
