#ifndef _SUNNEED_IPC_H_
#define _SUNNEED_IPC_H_

#define SUNNEED_LISTENER_URL "ipc:///tmp/sunneed.ipc"

#define SUNNEED_IPC_TEST_REQ_STR "REQ"
#define SUNNEED_IPC_TEST_REP_STR "REP"

#define SUNNEED_IPC_REQ_GET_DEVICE_HANDLE "HANDLE"

#define SUNNEED_IPC_REP_STATE_SUCCESS "YEAH"
#define SUNNEED_IPC_REP_STATE_FAILURE "SORRY"

#endif
