# specify base image
FROM paperspace/fastai

# Don't change dir or copy files. Instead use docker run -v to link files
#WORKDIR ~/power_mgmt_infra/src/sorter/docker/
#COPY . .

# install dependencies
#RUN pip3 install keras\
